/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campingparty;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author alumno
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        arrayGerentes = new ArrayList();
        g = new Gerente("admin","admin");
        arrayGerentes.add(g);
        
        
        clientes = new ArrayList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campingParty = new javax.swing.JLabel();
        etUsuario = new javax.swing.JLabel();
        etPass = new javax.swing.JLabel();
        fieldusuario = new javax.swing.JTextField();
        registro = new javax.swing.JButton();
        fieldpass = new javax.swing.JPasswordField();
        entrar = new javax.swing.JButton();
        btnGerente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campingParty.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        campingParty.setText("CAMPING PARTY");

        etUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etUsuario.setText("Usuario");

        etPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etPass.setText("Contraseña");

        registro.setText("Registrarse");
        registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroMouseClicked(evt);
            }
        });
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });

        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        btnGerente.setText("Gerente");
        btnGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registro)
                    .addComponent(etUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etPass, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldusuario)
                            .addComponent(fieldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(entrar)))
                .addGap(0, 95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGerente)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(campingParty)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(campingParty)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etUsuario)
                    .addComponent(fieldusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etPass)
                    .addComponent(fieldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registro)
                    .addComponent(entrar))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        // TODO add your handling code here:
        RegistroCliente registro = new RegistroCliente();
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registroActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        /**
         * Para quitar el apaño del boton de acceder al menu clientes,
         * comentar las siguientes 3 lineas y descomentar el resto.
         */
        Cliente cliente = new Cliente();
        cliente.setVisible(true);
        this.dispose();
        
        
                
                
        /*
        if(fieldusuario.getText().isEmpty() || fieldpass.getPassword().length==0){
           JOptionPane.showMessageDialog(this,"Debes introducir un usuario y una contraseña.","Alert",JOptionPane.WARNING_MESSAGE); 
        
        }
        else{
            //Comprobar login gerente
            for(Cliente i: clientes){
            if(i.getUser().equals(fieldusuario.getText())){
             
               Cliente cli = new Cliente(i.getUser(),i.getPassword(),i.getDNI(),i.getName(),i.getSurname());
               cli.setVisible(true);
               this.dispose();
            }
        }
        }
        */
        
        
    }//GEN-LAST:event_entrarActionPerformed

    private void registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_registroMouseClicked

    private void btnGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenteActionPerformed
        // TODO add your handling code here:
        //Comprobar login gerente
        for(Gerente ger: arrayGerentes){
            if(ger.getUser().equals(fieldusuario.getText())){
                String pass = fieldpass.getPassword().toString();
                if(ger.getPass().equals(pass)){
                    Gerente gerente = new Gerente(ger.getUser(), ger.getPass());
                    gerente.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this,"Los datos introducidos no son correctos.",
                            "Alert",JOptionPane.WARNING_MESSAGE); 
        
                }
            }
        }
    }//GEN-LAST:event_btnGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    
    //Array para dar de alta gerentes
    private ArrayList<Gerente> arrayGerentes;
    private Gerente g;
    //Array para dar de alta clientes
    private ArrayList<Cliente> clientes;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerente;
    private javax.swing.JLabel campingParty;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel etPass;
    private javax.swing.JLabel etUsuario;
    private javax.swing.JPasswordField fieldpass;
    private javax.swing.JTextField fieldusuario;
    private javax.swing.JButton registro;
    // End of variables declaration//GEN-END:variables
}
