/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import campingparty.Controlador;
import vista.Login;
import vista.ModificarReserva;
import vista.ReservaCliente;

/**
 *
 * @author christian
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    private String dni;
    public Cliente(Controlador controlador) {
        this.controlador = controlador;
        initComponents();
    }

    Cliente(Controlador controlador, String dni) {
        this.controlador=controlador;
        this.dni = dni;
         initComponents();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hacerReserva = new javax.swing.JButton();
        modificarReserva = new javax.swing.JButton();
        reservarActividad = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cancelarActividad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hacerReserva.setText("Hacer Reserva");
        hacerReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hacerReservaActionPerformed(evt);
            }
        });

        modificarReserva.setText("Cambiar fecha Reserva");
        modificarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarReservaActionPerformed(evt);
            }
        });

        reservarActividad.setText("Reservar Actividad");
        reservarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarActividadActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido!");

        cancelarActividad.setText("Cancelar Actividad");
        cancelarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(hacerReserva))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(modificarReserva))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelarActividad)
                            .addComponent(reservarActividad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(salir)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(hacerReserva)
                .addGap(18, 18, 18)
                .addComponent(modificarReserva)
                .addGap(18, 18, 18)
                .addComponent(reservarActividad)
                .addGap(18, 18, 18)
                .addComponent(cancelarActividad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(salir)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hacerReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hacerReservaActionPerformed
        // TODO add your handling code here:
        ReservaCliente rc = new ReservaCliente(controlador, true);
        rc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hacerReservaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Login login = new Login(controlador);
        login.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void reservarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarActividadActionPerformed
        ActividadesCliente actividadescliente = new ActividadesCliente(controlador, dni);// TODO add your handling code here:
        actividadescliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reservarActividadActionPerformed

    private void modificarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarReservaActionPerformed
        ModificarReserva modificarReserva = new ModificarReserva(controlador,dni);// TODO add your handling code here:
        modificarReserva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modificarReservaActionPerformed

    private void cancelarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActividadActionPerformed
        // TODO add your handling code here:
        CancelarActividadCliente cancelar = new CancelarActividadCliente(controlador, dni);
        cancelar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarActividadActionPerformed


    //VARIABLES PARA ALMACENAR USUARIO Y CONTRASEÑA DEL Cliente
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarActividad;
    private javax.swing.JButton hacerReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton modificarReserva;
    private javax.swing.JButton reservarActividad;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
    private Controlador controlador;
}
