/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.Login;
import vista.ModificarReserva;
import vista.ReservaCliente;

/**
 *
 * @author christian
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }
    
    //CONSTRUCTOR CON ARGUMENTOS
    public Cliente(String user, String password, String dni, String name, String surname){
        this.user = user;
        this.password = password;
        this.dni = dni;
        this.name = name;
        this.surname = surname;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hacerReserva = new javax.swing.JButton();
        modificarReserva = new javax.swing.JButton();
        reservarActividad = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cancelarActividad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hacerReserva.setText("Hacer Reserva");
        hacerReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hacerReservaActionPerformed(evt);
            }
        });

        modificarReserva.setText("Cambiar fecha Reserva");
        modificarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarReservaActionPerformed(evt);
            }
        });

        reservarActividad.setText("Reservar Actividad");
        reservarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarActividadActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido!");

        cancelarActividad.setText("Cancelar Actividad");
        cancelarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(hacerReserva))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(modificarReserva))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelarActividad)
                            .addComponent(reservarActividad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(salir)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(hacerReserva)
                .addGap(18, 18, 18)
                .addComponent(modificarReserva)
                .addGap(18, 18, 18)
                .addComponent(reservarActividad)
                .addGap(18, 18, 18)
                .addComponent(cancelarActividad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(salir)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hacerReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hacerReservaActionPerformed
        // TODO add your handling code here:
        ReservaCliente rc = new ReservaCliente();
        rc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hacerReservaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void reservarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarActividadActionPerformed
        ActividadesCliente actividadescliente = new ActividadesCliente();// TODO add your handling code here:
        actividadescliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reservarActividadActionPerformed

    private void modificarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarReservaActionPerformed
        ModificarReserva modificarReserva = new ModificarReserva();// TODO add your handling code here:
        modificarReserva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modificarReservaActionPerformed

    private void cancelarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActividadActionPerformed
        // TODO add your handling code here:
        CancelarActividadCliente cancelar = new CancelarActividadCliente();
        cancelar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarActividadActionPerformed


    //VARIABLES PARA ALMACENAR USUARIO Y CONTRASEÑA DEL Cliente
    private String user;
    private String password;
    private String dni;
    private String name;
    private String surname;
    
    public String getUser(){
        return this.user;
    }
    public String getPassword(){
        return this.user;
    }
    public String getDNI(){
        return this.dni;
    }
    public String getName(){
        return this.name;
    }
    public String getSurname(){
        return this.surname;
    }
    
    
    public void setUser(String user){
        this.user =  user;
    }
    public void setPassword(String password){
        this.password = password;
    }
    public void setDNI(String dni){
        this.dni = dni;
    }
    public void setName(String name){
        this.name = name;
    }
    public void setSurname(String surname){
        this.surname = surname;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarActividad;
    private javax.swing.JButton hacerReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton modificarReserva;
    private javax.swing.JButton reservarActividad;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
