/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import campingparty.Controlador;
import java.util.ArrayList;
import java.util.Date;
import vista.SeleccionarParcelas;
import vista.ReservaCliente;

/**
 *
 * @author MIRENA
 */
public class IntroducirDatosTienda extends javax.swing.JFrame {
    private int numTiendas = 0;
    private int tiendaActual = 1;
    private ArrayList nombres = new ArrayList();
    private ArrayList tamanyos = new ArrayList();
    Date entrada;
    Date salida;
    Controlador controlador;
    
    /**
     * Creates new form DatosTiendaCampaña
     * @param c
     * @param numTiendas
     * @param entrada
     * @param salida
     */
    public IntroducirDatosTienda(Controlador c, int numTiendas, Date entrada, Date salida) {
        this.controlador = c;
        this.numTiendas = numTiendas;
        this.entrada = entrada;
        this.salida = salida;
        initComponents();
        titulo.setText("Tienda de campaña " + tiendaActual);
        nombre.requestFocus();
        
        //Cargar parcelas en vista
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        tam = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        tamanyo = new javax.swing.JTextField();
        volver = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo.setText("Tienda de campaña");

        nom.setText("Nombre");

        tam.setText("Tamaño(cm3)");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        tamanyo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanyoActionPerformed(evt);
            }
        });

        volver.setText("volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        siguiente.setText("siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(siguiente)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tam)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tamanyo, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(nombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(titulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(titulo)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tam)
                    .addComponent(tamanyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver)
                    .addComponent(siguiente))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tamanyoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanyoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamanyoActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente(controlador);
        cliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        
        //Obtengo datos de la tienda actual
        nombres.add(nombre.getText());
        tamanyos.add(Integer.parseInt(tamanyo.getText()));
        
        //Paso a la tienda siguiente
        tiendaActual++;

        //Compruebo si hay tienda siguiente
        if(numTiendas < tiendaActual)
        {   //Si ya no faltan tiendas envío datos a la siguiente vista.
            SeleccionarParcelas parcelas = new SeleccionarParcelas(controlador, numTiendas, entrada, salida, nombres, tamanyos);
            parcelas.setVisible(true);
            this.dispose();
        }
        else
        {   //Si faltan tiendas reseteo valores
            nombre.setText(null);
            tamanyo.setText(null);
            nombre.requestFocus();
            titulo.setText("Tienda de campaña" + tiendaActual);
        }
        
        
    }//GEN-LAST:event_siguienteActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nom;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton siguiente;
    private javax.swing.JLabel tam;
    private javax.swing.JTextField tamanyo;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
