/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import campingparty.*;
import vista.RegistroCliente;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Arrays;
import Modelo.Camping;



/**
 *
 * @author alumno
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    private Controlador controlador;
   // private DAO dao;
  
    
    public Login(Controlador controlador) {
        this.controlador = controlador;
        
        //controlador.cargarDatosIniciales();
        
            
        //Inicio controlador del programa y cargo datos iniciales      
        initComponents();
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campingParty = new javax.swing.JLabel();
        etUsuario = new javax.swing.JLabel();
        etPass = new javax.swing.JLabel();
        fieldusuario = new javax.swing.JTextField();
        registro = new javax.swing.JButton();
        fieldpass = new javax.swing.JPasswordField();
        entrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campingParty.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        campingParty.setText("CAMPING PARTY");

        etUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etUsuario.setText("Usuario");

        etPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etPass.setText("Contraseña");

        fieldusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldusuarioActionPerformed(evt);
            }
        });

        registro.setText("Registrarse");
        registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroMouseClicked(evt);
            }
        });
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });

        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registro)
                    .addComponent(etUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etPass, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldusuario)
                            .addComponent(fieldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(entrar)))
                .addGap(0, 95, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(campingParty)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(campingParty)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etUsuario)
                    .addComponent(fieldusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etPass)
                    .addComponent(fieldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registro)
                    .addComponent(entrar))
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed

        // TODO add your handling code here:
        RegistroCliente registrocliente = new RegistroCliente(controlador);
        registrocliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registroActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        /**
         * Para quitar el apaño del boton de acceder al menu clientes,
         * comentar las siguientes 3 lineas y descomentar el resto.
         */
        String pass_string = new String (fieldpass.getPassword());
                  
       if(fieldusuario.getText().isEmpty() || fieldpass.getPassword().length==0){
           JOptionPane.showMessageDialog(this,"Debes introducir un usuario y una contraseña.","Alert",JOptionPane.WARNING_MESSAGE);        
       }
        else{
           
            if(controlador.comprobarExistenciaCliente(fieldusuario.getText(), pass_string )){
                Cliente cliente = new Cliente(controlador, controlador.devolverDni(fieldusuario.getText()));
                cliente.setVisible(true);
                this.dispose();
            }
            else{
                if(controlador.comprobarLoginGerente(fieldusuario.getText(), pass_string)){
                    MenuGerente mg = new MenuGerente(controlador);
                    mg.setVisible(true);
                    this.dispose();
                }else{          
                   JOptionPane.showMessageDialog(this,"Error: Usuario o contraseña incorrectos","Alert",JOptionPane.WARNING_MESSAGE);
                }
            }               
       }
        
      
    
        
        
    }//GEN-LAST:event_entrarActionPerformed

    private void registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_registroMouseClicked

    private void fieldusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldusuarioActionPerformed

    /**
     * @param args the command line arguments
     */


    

   
    //Array para dar de alta clientes
   
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campingParty;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel etPass;
    private javax.swing.JLabel etUsuario;
    private javax.swing.JPasswordField fieldpass;
    private javax.swing.JTextField fieldusuario;
    private javax.swing.JButton registro;
    // End of variables declaration//GEN-END:variables
}
