/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import campingparty.Controlador;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Graphics;
import Images.Imagen;



/**
 *
 * @author alex
 */
public class SeleccionarParcelas extends javax.swing.JFrame {
    private Date entrada;
    private Date salida;
    private Controlador controlador;
    private int numTiendas;
    private ArrayList nombres;
    private ArrayList tamanyos;
    private ArrayList coordX;
    private ArrayList coordY;
    boolean ocupada = false;
    private BufferedImage image;
    private ArrayList<String> id;
    private boolean esCliente;
    private int numParcelas;
    private ArrayList<String> ocupade;
    
    
    
    /**    CONSTRUCTOR
     * Creates new form SeleccionarParcelas
     * @param nombres
     * @param tamanyos
     * @param entrada
     * @param salida
     */
    public SeleccionarParcelas(Controlador c, int numTiendas, Date entrada, Date salida, ArrayList nombres, ArrayList tamanyos, boolean esC){
        this.controlador = c;
        this.numTiendas = numTiendas;
        this.entrada = entrada;
        this.salida = salida;
        this.nombres = nombres;
        this.tamanyos = tamanyos;
        this.esCliente = esC;
        this.numParcelas = 0;
        ocupade = new ArrayList();
        id = new ArrayList();
        initComponents();
        anyadirParcelasAVista();
        anyadirParcela.setEnabled(true);
        finalizar.setEnabled(true);
        mostrarOcupada.setText("Libre");
        
//        Imagen im = new Imagen(imagenParcelas);
//        imagenParcelas.add(im).repaint();
        
        
        
        
        
        
//        try {
//            image = ImageIO.read(new File("/Images/Parcelas.png"));
//        } catch (IOException ex) {
//            Logger.getLogger(SeleccionarParcelas.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        imagenParcelas.repaint();
        //Cargar datos de las parcelas.
    }
    
//    protected void paintComponent(Graphics g) {
//        paintComponent(g);
//        g.drawImage(image, 0, 0, this); // see javadoc for more info on the parameters            
//    }
    
    
    
    
    private void anyadirParcelasAVista(){
        int tam = controlador.numeroDeParcelas();
        ArrayList<String> id = controlador.getIDs();
        for(int i=0; i<tam; i++)
        {
            if(!controlador.parcelaOcupada(id.get(i),entrada,salida))
            {
                comboParcelas.addItem(id.get(i));
                ocupade.add("Libre");
            }
        }
    }
        

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboParcelas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        finalizar = new javax.swing.JButton();
        anyadirParcela = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imagenParcelas = new javax.swing.JPanel();
        mostrarTamanyo = new javax.swing.JLabel();
        mostrarLuz = new javax.swing.JLabel();
        mostrarPrecio = new javax.swing.JLabel();
        mostrarOcupada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Parcelas disponibles");

        comboParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboParcelasActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecciona parcela:");

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        finalizar.setText("Finalizar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });

        anyadirParcela.setText("Añadir otra parcela");
        anyadirParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anyadirParcelaActionPerformed(evt);
            }
        });

        jLabel3.setText("Tamaño:");

        jLabel4.setText("Luz acesible:");

        jLabel5.setText("Precio por día:");

        jLabel6.setText("Ocupada:");

        javax.swing.GroupLayout imagenParcelasLayout = new javax.swing.GroupLayout(imagenParcelas);
        imagenParcelas.setLayout(imagenParcelasLayout);
        imagenParcelasLayout.setHorizontalGroup(
            imagenParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        imagenParcelasLayout.setVerticalGroup(
            imagenParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mostrarTamanyo.setText("tam");

        mostrarLuz.setText("tam");

        mostrarPrecio.setText("tam");

        mostrarOcupada.setText("tam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(volver)
                .addGap(86, 86, 86)
                .addComponent(anyadirParcela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(finalizar)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mostrarLuz)
                                            .addComponent(mostrarTamanyo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(comboParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imagenParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mostrarOcupada)
                                            .addComponent(mostrarPrecio)))
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mostrarTamanyo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(mostrarLuz)))
                    .addComponent(imagenParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mostrarPrecio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mostrarOcupada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver)
                    .addComponent(finalizar)
                    .addComponent(anyadirParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        //DatosTiendaCampanya tienda = new DatosTiendaCampanya(ArrayList<String>);
        Cliente cliente = new Cliente(controlador);
        cliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        // TODO add your handling code here:

        //código de guardar los datos y hacer la reserva bien.
        if(esCliente){ //parte de alex
            
            //Creo reserva con las parcelas.
            numParcelas = controlador.getNumParcelas() + 1;     //No se para que es esto
            id.add((String)comboParcelas.getSelectedItem());    //Obtengo Id de la parcela a añadir
            controlador.nuevaReserva(id, numTiendas, entrada, salida, nombres, tamanyos, numParcelas);  //Creo nueva reserva
            
            //Informo del resultado de la transacción y cierro la ventana.
            JOptionPane.showMessageDialog(this, "Reserva Realizada con éxito");
            
            //Abro la vista del cliente de nuevo.
            Cliente cliente = new Cliente(controlador);
            cliente.setVisible(true);
            controlador.setNumParcelas(0);      //No se para que es esto
            
            this.dispose();
        }else{ //Parte de ivan creo
            //Guardar parcela:
            numParcelas = controlador.getNumParcelas() + 1;
            controlador.nuevaEntrada(id, numTiendas, entrada, salida, nombres, tamanyos, numParcelas);
            controlador.setNumParcelas(0);
            JOptionPane.showMessageDialog(this, "Entrada Realizada con éxito. Bienvenid@");
            this.dispose();
        }
    }//GEN-LAST:event_finalizarActionPerformed

    private void anyadirParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anyadirParcelaActionPerformed

        id.add((String)comboParcelas.getSelectedItem());        //Añado una parcela para la reserva actual
        ocupade.set(comboParcelas.getSelectedIndex(),"Ocupada");//Pongo parcela añadida como ocupada para no añadirla de nuevo
        
        ///Esto de augmentar numero no se que hace
        controlador.aumentarNumParcelas();
        anyadirParcela.setEnabled(false);
        finalizar.setEnabled(false);
        mostrarOcupada.setText("Ocupada");
    }//GEN-LAST:event_anyadirParcelaActionPerformed

    private void comboParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboParcelasActionPerformed
        // TODO add your handling code here:
        
        //actualizar datos de la vista.
        
        //obtener id de combobox
        String id = (String)comboParcelas.getSelectedItem();
        //Buscar la parcela
        //obtener y mostrar datos.
        mostrarTamanyo.setText(controlador.getTamanyo(id));
            mostrarLuz.setText(controlador.getLuz(id));
         mostrarPrecio.setText(controlador.getPrecio(id));
        if (ocupade != null && !ocupade.isEmpty())
            id = (String)ocupade.get(comboParcelas.getSelectedIndex());
        mostrarOcupada.setText(id);
        if(id.equals("Libre"))
        {
            anyadirParcela.setEnabled(true);
            finalizar.setEnabled(true);
        } else
        {
            anyadirParcela.setEnabled(false);
            finalizar.setEnabled(false);
        }    
    }//GEN-LAST:event_comboParcelasActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anyadirParcela;
    private javax.swing.JComboBox<String> comboParcelas;
    private javax.swing.JButton finalizar;
    private javax.swing.JPanel imagenParcelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel mostrarLuz;
    private javax.swing.JLabel mostrarOcupada;
    private javax.swing.JLabel mostrarPrecio;
    private javax.swing.JLabel mostrarTamanyo;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
