/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import campingparty.Controlador;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Graphics;



/**
 *
 * @author alex
 */
public class SeleccionarParcelas extends javax.swing.JFrame {
    private Date entrada;
    private Date salida;
    private Controlador controlador;
    private int numTiendas;
    private ArrayList nombres;
    private ArrayList tamanyos;
    private ArrayList coordX;
    private ArrayList coordY;
    boolean ocupada = false;
    private BufferedImage image;
    private String id;
    private boolean esCliente;
    private int numParcelas;
    
    
    
    /**    CONSTRUCTOR
     * Creates new form SeleccionarParcelas
     * @param nombres
     * @param tamanyos
     * @param entrada
     * @param salida
     */
    public SeleccionarParcelas(Controlador c, int numTiendas, Date entrada, Date salida, ArrayList nombres, ArrayList tamanyos, boolean esC){
        this.controlador = c;
        this.numTiendas = numTiendas;
        this.entrada = entrada;
        this.salida = salida;
        this.nombres = nombres;
        this.tamanyos = tamanyos;
        this.esCliente = esC;
        this.numParcelas = 0;
        initComponents();
        anyadirParcelasAVista();
        
        
        
        
        
        
//        try {
//            image = ImageIO.read(new File("/Images/Parcelas.png"));
//        } catch (IOException ex) {
//            Logger.getLogger(SeleccionarParcelas.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        imagenParcelas.repaint();
        //Cargar datos de las parcelas.
    }
    
//    protected void paintComponent(Graphics g) {
//        paintComponent(g);
//        g.drawImage(image, 0, 0, this); // see javadoc for more info on the parameters            
//    }
    
    
    
    private void anyadirParcelasAVista(){
        int tam = controlador.numeroDeParcelas();
        ArrayList<String> x = controlador.getPosicionesX();
        ArrayList<String> y = controlador.getPosicionesY();
        for(int i=0; i<tam; i++)
        {
            comboLetras.addItem(x.get(i));
            comboNumeros.addItem(y.get(i));
        }
    }
        

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboLetras = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        finalizar = new javax.swing.JButton();
        anyadirParcela = new javax.swing.JButton();
        comboNumeros = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imagenParcelas = new javax.swing.JPanel();
        mostrarTamanyo = new javax.swing.JLabel();
        mostrarLuz = new javax.swing.JLabel();
        mostrarPrecio = new javax.swing.JLabel();
        mostrarOcupada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Parcelas disponibles");

        comboLetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLetrasActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecciona parcela:");

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        finalizar.setText("Finalizar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });

        anyadirParcela.setText("Añadir otra parcela");
        anyadirParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anyadirParcelaActionPerformed(evt);
            }
        });

        comboNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumerosActionPerformed(evt);
            }
        });

        jLabel3.setText("Tamaño:");

        jLabel4.setText("Luz acesible:");

        jLabel5.setText("Precio por día:");

        jLabel6.setText("Ocupada:");

        javax.swing.GroupLayout imagenParcelasLayout = new javax.swing.GroupLayout(imagenParcelas);
        imagenParcelas.setLayout(imagenParcelasLayout);
        imagenParcelasLayout.setHorizontalGroup(
            imagenParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        imagenParcelasLayout.setVerticalGroup(
            imagenParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mostrarTamanyo.setText("tam");

        mostrarLuz.setText("tam");

        mostrarPrecio.setText("tam");

        mostrarOcupada.setText("tam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(volver)
                .addGap(86, 86, 86)
                .addComponent(anyadirParcela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(finalizar)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(comboLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mostrarOcupada)
                                            .addComponent(mostrarPrecio))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(mostrarLuz)
                                                    .addComponent(mostrarTamanyo))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(imagenParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mostrarTamanyo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(mostrarLuz)))
                    .addComponent(imagenParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mostrarPrecio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mostrarOcupada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver)
                    .addComponent(finalizar)
                    .addComponent(anyadirParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        //DatosTiendaCampanya tienda = new DatosTiendaCampanya(ArrayList<String>);
        Cliente cliente = new Cliente(controlador);
        cliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        // TODO add your handling code here:
        
        
        
        JOptionPane.showMessageDialog(this, "Reserva Realizada con éxito");

        //código de guardar los datos y hacer la reserva bien.
        if(esCliente){
            
            //TODO Pasar el cliente al metodo nuevaReserva
            
            //Guardar parcela:
            numParcelas = controlador.getNumParcelas() + 1;
            controlador.nuevaReserva(id, numTiendas, entrada, salida, nombres, tamanyos, numParcelas);
            Cliente cliente = new Cliente(controlador);
            cliente.setVisible(true);
            controlador.setNumParcelas(0);
            this.dispose();
        }else{
            //Guardar parcela:
            numParcelas = controlador.getNumParcelas() + 1;
            controlador.nuevaReserva(id, numTiendas, entrada, salida, nombres, tamanyos, numParcelas);
            controlador.setNumParcelas(0);
            this.dispose();
        }
    }//GEN-LAST:event_finalizarActionPerformed

    private void comboNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumerosActionPerformed
        // TODO add your handling code here:
        
        //actualizar datos de la vista.
        
        //obtener ambos combobox
        String x = (String)comboLetras.getSelectedItem();
        String y = (String)comboNumeros.getSelectedItem();
        //juntarlos para conseguir el id
        id = x+y;
        //Buscar la parcela
        //obtener y mostrar datos.
        mostrarTamanyo.setText(controlador.getTamanyo(id));
            mostrarLuz.setText(controlador.getLuz(id));
         mostrarPrecio.setText(controlador.getPrecio(id));
        mostrarOcupada.setText(controlador.getOcupada(id));
    }//GEN-LAST:event_comboNumerosActionPerformed

    private void anyadirParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anyadirParcelaActionPerformed
        // TODO add your handling code here:
        //Poner parcela anterior como ocupada
        ///????
        controlador.aumentarNumParcelas();
        //Guardar parcela:
        controlador.nuevaReserva(id, numTiendas, entrada, salida, nombres, tamanyos, numParcelas);
    }//GEN-LAST:event_anyadirParcelaActionPerformed

    private void comboLetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLetrasActionPerformed
        // TODO add your handling code here:
        
        //actualizar datos de la vista.
        
        //obtener ambos combobox
        String x = (String)comboLetras.getSelectedItem();
        String y = (String)comboNumeros.getSelectedItem();
        //juntarlos para conseguir el id
        id = x+y;
        //Buscar la parcela
        //obtener y mostrar datos.
        mostrarTamanyo.setText(controlador.getTamanyo(id));
            mostrarLuz.setText(controlador.getLuz(id));
         mostrarPrecio.setText(controlador.getPrecio(id));
        mostrarOcupada.setText(controlador.getOcupada(id));
    }//GEN-LAST:event_comboLetrasActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anyadirParcela;
    private javax.swing.JComboBox<String> comboLetras;
    private javax.swing.JComboBox<String> comboNumeros;
    private javax.swing.JButton finalizar;
    private javax.swing.JPanel imagenParcelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel mostrarLuz;
    private javax.swing.JLabel mostrarOcupada;
    private javax.swing.JLabel mostrarPrecio;
    private javax.swing.JLabel mostrarTamanyo;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
